name: Daily Digest

on:
  schedule:
    - cron: '0 23 * * *' # Runs at 23:00 UTC every day

jobs:
  trigger_api:
    runs-on: ubuntu-latest
    steps:
      - name: Curl API
        run: |
          curl https://x7lreie3ib.execute-api.eu-central-1.amazonaws.com/live/daily_digest